apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-http
  labels:
    app: kuber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-server-http
  template:
    metadata:
      labels:
        app: http-server-http
    spec:
      containers:
      - name: kuber-app
        image: bakavets/kuber:v1.0-unhealthy
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: kuber-service-http
spec:
  selector:
    app: http-server-http
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30003
  type: NodePort